/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;
import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.*;

/**
 *
 * @author suraj
 */
public class PrintReceipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt() {
        initComponents();
        getRecords();
        Container c = getContentPane();
        c.setBackground(new Color(0,153,153));
        
        
    }
    
    
    
    public void getRecords(){
        
        
        try {
            Connection con = DB_Conn.getConnection();
            PreparedStatement pst = con.prepareStatement("Select * from fees_details order by receipt_no desc limit 1");
            ResultSet rs = pst.executeQuery();
            rs.next();
            txt_receiptno.setText(rs.getString("receipt_no"));
            txt_paymentmode.setText(rs.getString("payment_mode"));
            
            String paymentmode = rs.getString("payment_mode");
            
            if (paymentmode.equalsIgnoreCase("cash")){
                lbl_cheque_dd.setText("Cheque No :");
                txt_cheque_dd.setText("-");
                txt_bankname.setText("-");
                
            }
            
            if (paymentmode.equalsIgnoreCase("cheque")){
                lbl_cheque_dd.setText("Cheque No :");
                txt_cheque_dd.setText(rs.getString("cheque_no"));
                txt_bankname.setText(rs.getString("bank_name"));
                
            }
            
            if (paymentmode.equalsIgnoreCase("dd")){
                lbl_cheque_dd.setText("DD No :");
                txt_cheque_dd.setText(rs.getString("dd_no"));
                txt_bankname.setText(rs.getString("bank_name"));
                
            }
            
            if (paymentmode.equalsIgnoreCase("credit/debit card")){
                lbl_cheque_dd.setText("Cheque No :");
                txt_cheque_dd.setText("-");
                txt_bankname.setText(rs.getString("bank_name"));
                
            }
            
            txt_receivedfrom.setText(rs.getString("student_name"));
            
            
            txt_date.setText(rs.getString("date"));
            txt_gstin.setText(rs.getString("gstin"));
            txt_year1.setText(rs.getString("year1"));
            txt_year2.setText(rs.getString("year2"));
            
            lbl_coursename.setText(rs.getString("courses"));
            txt_initialamount.setText(rs.getString("amount"));
            txt_cgst.setText(rs.getString("cgst"));
            txt_sgst.setText(rs.getString("sgst"));
            txt_totalamount.setText(rs.getString("total_amount"));
            txt_totalinwords.setText(rs.getString("total_in_words"));
            txt_remarks.setText(rs.getString("remark"));
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }

        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsideBar = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        panelEdit = new javax.swing.JPanel();
        lbl_edit = new javax.swing.JLabel();
        panelSearchrecord = new javax.swing.JPanel();
        btnHome14 = new javax.swing.JLabel();
        panelEditcourse = new javax.swing.JPanel();
        btnHome66 = new javax.swing.JLabel();
        panelViewallRec = new javax.swing.JPanel();
        lbl_viewallrec = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btnHome222 = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        lbl_logout = new javax.swing.JLabel();
        panelPrint = new javax.swing.JPanel();
        lbl_print = new javax.swing.JLabel();
        panelprint = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_gstin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_receiptno = new javax.swing.JLabel();
        lbl_paymentmode = new javax.swing.JLabel();
        lbl_cheque_dd = new javax.swing.JLabel();
        lbl_bankname = new javax.swing.JLabel();
        lbl_receivedfrom = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_paymentmode = new javax.swing.JLabel();
        txt_cheque_dd = new javax.swing.JLabel();
        txt_bankname = new javax.swing.JLabel();
        txt_receivedfrom = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_gstin = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        txt_totalamount = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl_coursename = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_initialamount = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txt_totalinwords = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txt_remarks = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_year1 = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(1963, 1092));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsideBar.setBackground(new java.awt.Color(0, 102, 102));
        panelsideBar.setPreferredSize(new java.awt.Dimension(540, 1040));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome.setBackground(new java.awt.Color(0, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelHomeMouseExited(evt);
            }
        });
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Mongolian Baiti", 0, 28)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnHome.setText("  Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        panelHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        panelsideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 290, 50));

        panelEdit.setBackground(new java.awt.Color(0, 102, 102));
        panelEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEditMouseExited(evt);
            }
        });
        panelEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_edit.setFont(new java.awt.Font("Mongolian Baiti", 0, 28)); // NOI18N
        lbl_edit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        lbl_edit.setText("  Edit");
        lbl_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_editMouseExited(evt);
            }
        });
        panelEdit.add(lbl_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        panelsideBar.add(panelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 290, 50));

        panelSearchrecord.setBackground(new java.awt.Color(0, 102, 102));
        panelSearchrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelSearchrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSearchrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSearchrecordMouseExited(evt);
            }
        });
        panelSearchrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome14.setFont(new java.awt.Font("Mongolian Baiti", 0, 28)); // NOI18N
        btnHome14.setForeground(new java.awt.Color(255, 255, 255));
        btnHome14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search2.png"))); // NOI18N
        btnHome14.setText(" Search Record");
        btnHome14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHome14MouseClicked(evt);
            }
        });
        panelSearchrecord.add(btnHome14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, 270, 30));

        panelsideBar.add(panelSearchrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 290, 50));

        panelEditcourse.setBackground(new java.awt.Color(0, 102, 102));
        panelEditcourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelEditcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEditcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEditcourseMouseExited(evt);
            }
        });
        panelEditcourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome66.setFont(new java.awt.Font("Mongolian Baiti", 0, 28)); // NOI18N
        btnHome66.setForeground(new java.awt.Color(255, 255, 255));
        btnHome66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btnHome66.setText("  Edit Courses");
        btnHome66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHome66MouseClicked(evt);
            }
        });
        panelEditcourse.add(btnHome66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        panelsideBar.add(panelEditcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 290, 50));

        panelViewallRec.setBackground(new java.awt.Color(0, 102, 102));
        panelViewallRec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelViewallRec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelViewallRecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelViewallRecMouseExited(evt);
            }
        });
        panelViewallRec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_viewallrec.setFont(new java.awt.Font("Mongolian Baiti", 0, 28)); // NOI18N
        lbl_viewallrec.setForeground(new java.awt.Color(255, 255, 255));
        lbl_viewallrec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        lbl_viewallrec.setText(" View All Records");
        lbl_viewallrec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viewallrecMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_viewallrecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_viewallrecMouseExited(evt);
            }
        });
        panelViewallRec.add(lbl_viewallrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 30));

        panelsideBar.add(panelViewallRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 310, 50));

        panelBack.setBackground(new java.awt.Color(0, 102, 102));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBackMouseExited(evt);
            }
        });
        panelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome222.setFont(new java.awt.Font("Mongolian Baiti", 0, 28)); // NOI18N
        btnHome222.setForeground(new java.awt.Color(255, 255, 255));
        btnHome222.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/back1.png"))); // NOI18N
        btnHome222.setText("  Back");
        btnHome222.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHome222MouseClicked(evt);
            }
        });
        panelBack.add(btnHome222, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        panelsideBar.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 290, 50));

        panelLogout.setBackground(new java.awt.Color(0, 102, 102));
        panelLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLogoutMouseExited(evt);
            }
        });
        panelLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_logout.setFont(new java.awt.Font("Mongolian Baiti", 0, 28)); // NOI18N
        lbl_logout.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        lbl_logout.setText("  Logout");
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseExited(evt);
            }
        });
        panelLogout.add(lbl_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        panelsideBar.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 290, 50));

        panelPrint.setBackground(new java.awt.Color(0, 102, 102));
        panelPrint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelPrintMouseExited(evt);
            }
        });
        panelPrint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_print.setFont(new java.awt.Font("Mongolian Baiti", 0, 28)); // NOI18N
        lbl_print.setForeground(new java.awt.Color(255, 255, 255));
        lbl_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/printer-.png"))); // NOI18N
        lbl_print.setText("  Print");
        lbl_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_printMouseExited(evt);
            }
        });
        panelPrint.add(lbl_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        panelsideBar.add(panelPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 290, 50));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 940));

        panelprint.setBackground(new java.awt.Color(255, 255, 255));
        panelprint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setText("Shri. Gopinath Mahadeo Vedak Pratisthan's");
        panelprint.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 102));
        jLabel12.setText("G. M. Vedak Institute of Technology, Tala");
        panelprint.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 470, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setText("             College Of Engineering(3447)");
        panelprint.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setText("Approved by AICTE & DTE Recognized by the Govt.of Maharashtra & Affiliated to University of Mumbai");
        panelprint.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/Screenshot 2023-06-17 154344.png"))); // NOI18N
        panelprint.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, 140));

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelprint.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1020, 10));

        lbl_gstin.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lbl_gstin.setText("GSTIN No :");
        panelprint.add(lbl_gstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 80, 20));

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel4.setText("Receipt no :    GMVIT -");
        panelprint.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 160, 20));

        txt_receiptno.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txt_receiptno.setText("Receipt no ");
        panelprint.add(txt_receiptno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 90, 20));

        lbl_paymentmode.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lbl_paymentmode.setText("Payment Mode :");
        panelprint.add(lbl_paymentmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 120, 20));

        lbl_cheque_dd.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lbl_cheque_dd.setText("cheque_dd :");
        panelprint.add(lbl_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 90, 20));

        lbl_bankname.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lbl_bankname.setText("Bank name :");
        panelprint.add(lbl_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 90, 20));

        lbl_receivedfrom.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lbl_receivedfrom.setText("Received from :");
        panelprint.add(lbl_receivedfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 120, 20));

        jLabel14.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel14.setText("Amount (Rs.)");
        panelprint.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 100, 20));

        txt_paymentmode.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txt_paymentmode.setText("payment mode");
        panelprint.add(txt_paymentmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 160, 20));

        txt_cheque_dd.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txt_cheque_dd.setText("cheque dd");
        panelprint.add(txt_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 160, 20));

        txt_bankname.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txt_bankname.setText("bank name");
        panelprint.add(txt_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 160, 20));

        txt_receivedfrom.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txt_receivedfrom.setText("received from");
        panelprint.add(txt_receivedfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 160, 20));

        jLabel19.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel19.setText("--");
        panelprint.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 20, 20));

        txt_gstin.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txt_gstin.setText("gstin");
        panelprint.add(txt_gstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 200, 20));

        jSeparator1.setBackground(new java.awt.Color(51, 0, 51));
        panelprint.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 680, 220, 10));

        jSeparator2.setBackground(new java.awt.Color(51, 0, 51));
        panelprint.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 1020, 10));

        jLabel21.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel21.setText("The following payment in the college office for the year");
        panelprint.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 400, 20));

        txt_totalamount.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txt_totalamount.setText("total");
        panelprint.add(txt_totalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, 130, 20));

        jLabel23.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel23.setText("Head");
        panelprint.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 50, 20));

        jLabel24.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel24.setText("Sr No.");
        panelprint.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 50, 20));

        jLabel25.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel25.setText("1");
        panelprint.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 80, 20));

        lbl_coursename.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lbl_coursename.setText("1");
        panelprint.add(lbl_coursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 190, 20));

        jLabel27.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel27.setText("cgst (9%)");
        panelprint.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 90, 20));

        jLabel28.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel28.setText("Office Signature");
        panelprint.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 690, 120, 20));

        txt_initialamount.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txt_initialamount.setText("amount");
        panelprint.add(txt_initialamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 130, 20));

        txt_cgst.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txt_cgst.setText("cgst");
        panelprint.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, 130, 20));

        txt_sgst.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txt_sgst.setText("sgst");
        panelprint.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 570, 140, 20));

        jSeparator3.setBackground(new java.awt.Color(51, 0, 51));
        panelprint.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1020, 10));

        jLabel32.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel32.setText("sgst (9%)");
        panelprint.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 100, 20));

        jLabel33.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel33.setText("Total in words :");
        panelprint.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 120, 20));

        txt_totalinwords.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txt_totalinwords.setText("total in words");
        panelprint.add(txt_totalinwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 430, 20));

        jLabel35.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel35.setText("Remarks : ");
        panelprint.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, 80, 20));

        txt_remarks.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txt_remarks.setText("remarks ");
        panelprint.add(txt_remarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, 360, 20));

        jSeparator4.setBackground(new java.awt.Color(51, 0, 51));
        panelprint.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, 220, 10));

        txt_year1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txt_year1.setText("2021");
        panelprint.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 40, 20));

        txt_year2.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txt_year2.setText("2022");
        panelprint.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 40, 20));

        lbl_date.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lbl_date.setText("Date :");
        panelprint.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 50, 20));

        txt_date.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txt_date.setText("Date ");
        panelprint.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 90, 20));

        getContentPane().add(panelprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 1020, 890));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Print Receipt");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 250, 40));

        setSize(new java.awt.Dimension(1558, 907));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseEntered
        Color clr = new Color(0,153,153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_panelHomeMouseEntered

    private void panelHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseExited
        Color clr = new Color(0,102,102);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_panelHomeMouseExited

    private void panelEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditMouseEntered
        Color c = new Color(0,153,153);
        panelEdit.setBackground(c);
    }//GEN-LAST:event_panelEditMouseEntered

    private void panelEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditMouseExited
        Color c = new Color(0,102,102);
        panelEdit.setBackground(c);
    }//GEN-LAST:event_panelEditMouseExited

    private void panelSearchrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchrecordMouseEntered
        Color clr = new Color(0,153,153);
        panelSearchrecord.setBackground(clr);
    }//GEN-LAST:event_panelSearchrecordMouseEntered

    private void panelSearchrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchrecordMouseExited
        Color clr = new Color(0,102,102);
        panelSearchrecord.setBackground(clr);
    }//GEN-LAST:event_panelSearchrecordMouseExited

    private void panelEditcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditcourseMouseEntered
        Color clr = new Color(0,153,153);
        panelEditcourse.setBackground(clr);
    }//GEN-LAST:event_panelEditcourseMouseEntered

    private void panelEditcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditcourseMouseExited
        Color clr = new Color(0,102,102);
        panelEditcourse.setBackground(clr);
    }//GEN-LAST:event_panelEditcourseMouseExited

    private void panelViewallRecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewallRecMouseEntered
        Color c = new Color(0,153,153);
        panelViewallRec.setBackground(c);
    }//GEN-LAST:event_panelViewallRecMouseEntered

    private void panelViewallRecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewallRecMouseExited
        Color c = new Color(0,102,102);
        panelViewallRec.setBackground(c);
    }//GEN-LAST:event_panelViewallRecMouseExited

    private void panelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBackMouseEntered
        Color clr = new Color(0,153,153);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_panelBackMouseEntered

    private void panelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBackMouseExited
        Color clr = new Color(0,102,102);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_panelBackMouseExited

    private void panelLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseEntered
        Color c = new Color(0,153,153);
        panelLogout.setBackground(c);
    }//GEN-LAST:event_panelLogoutMouseEntered

    private void panelLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseExited
        Color c = new Color(0,102,102);
        panelLogout.setBackground(c);
    }//GEN-LAST:event_panelLogoutMouseExited

    private void panelPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPrintMouseEntered
        Color c = new Color(0,153,153);
        panelPrint.setBackground(c);
    }//GEN-LAST:event_panelPrintMouseEntered

    private void panelPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPrintMouseExited
        Color c = new Color(0,102,102);
        panelPrint.setBackground(c);
    }//GEN-LAST:event_panelPrintMouseExited

    private void lbl_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_printMouseClicked
        
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
            
        job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                pf.setOrientation(PageFormat.LANDSCAPE);
                if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panelprint.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_lbl_printMouseClicked

    private void lbl_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_editMouseClicked
        updateFeedetails u = new updateFeedetails();
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_editMouseClicked

    private void lbl_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_editMouseEntered
 
        
    }//GEN-LAST:event_lbl_editMouseEntered

    private void lbl_viewallrecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewallrecMouseEntered
//        Color c = new Color(0,153,153);
//        lbl_viewallrec.setBackground(c);
    }//GEN-LAST:event_lbl_viewallrecMouseEntered

    private void lbl_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_editMouseExited
      
    }//GEN-LAST:event_lbl_editMouseExited

    private void lbl_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_printMouseEntered

    }//GEN-LAST:event_lbl_printMouseEntered

    private void lbl_printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_printMouseExited

    }//GEN-LAST:event_lbl_printMouseExited

    private void lbl_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseEntered

    }//GEN-LAST:event_lbl_logoutMouseEntered

    private void lbl_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseExited

    }//GEN-LAST:event_lbl_logoutMouseExited

    private void lbl_viewallrecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewallrecMouseExited
//        Color c = new Color(0,102,102);
//        lbl_viewallrec.setBackground(c);
    }//GEN-LAST:event_lbl_viewallrecMouseExited

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
         Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHome14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome14MouseClicked
        SearchRecord sr = new SearchRecord();
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHome14MouseClicked

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        // TODO add your handling code here:
        Login_page login = new Login_page();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void btnHome222MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome222MouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHome222MouseClicked

    private void btnHome66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome66MouseClicked
        // TODO add your handling code here:
         EditCourse ec = new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHome66MouseClicked

    private void lbl_viewallrecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewallrecMouseClicked
        // TODO add your handling code here:
        viewAllRecords var = new viewAllRecords();
        var.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_viewallrecMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnHome14;
    private javax.swing.JLabel btnHome222;
    private javax.swing.JLabel btnHome66;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_bankname;
    private javax.swing.JLabel lbl_cheque_dd;
    private javax.swing.JLabel lbl_coursename;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_edit;
    private javax.swing.JLabel lbl_gstin;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_paymentmode;
    private javax.swing.JLabel lbl_print;
    private javax.swing.JLabel lbl_receivedfrom;
    private javax.swing.JLabel lbl_viewallrec;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JPanel panelEditcourse;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelPrint;
    private javax.swing.JPanel panelSearchrecord;
    private javax.swing.JPanel panelViewallRec;
    private javax.swing.JPanel panelprint;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JLabel txt_bankname;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_cheque_dd;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_gstin;
    private javax.swing.JLabel txt_initialamount;
    private javax.swing.JLabel txt_paymentmode;
    private javax.swing.JLabel txt_receiptno;
    private javax.swing.JLabel txt_receivedfrom;
    private javax.swing.JLabel txt_remarks;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_totalamount;
    private javax.swing.JLabel txt_totalinwords;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
