/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author suraj
 */
public class viewAllRecords extends javax.swing.JFrame {

    /**
     * Creates new form viewAllRecords
     */
    public viewAllRecords() {
        initComponents();
        setDataToTable();
        
        
    }
    
    
      
    public void setDataToTable(){
        try {
            Connection con = DB_Conn.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from fees_details");
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                
                String receiptNo = rs.getString("receipt_no");
                String rollNo = rs.getString("roll_no");
                String studentname = rs.getString("student_name");
                String course = rs.getString("courses");
                String paymentMode = rs.getString("payment_mode");
                String amount  =rs.getString("total_amount");
                String date = rs.getString("date");
                String remark = rs.getString("remark");
                
                Object[] obj = {receiptNo,rollNo,studentname,course,paymentMode,amount,date,remark};
                 
                DefaultTableModel model = (DefaultTableModel)tbl_records.getModel();
                model.addRow(obj);
                
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsideBar = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        btnHome1 = new javax.swing.JLabel();
        panelSearchrecord = new javax.swing.JPanel();
        btnHome14 = new javax.swing.JLabel();
        panelEditcourse = new javax.swing.JPanel();
        btnHome66 = new javax.swing.JLabel();
        panelViewallRec = new javax.swing.JPanel();
        btnHome170 = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btnHome222 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_records = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsideBar.setBackground(new java.awt.Color(0, 102, 102));
        panelsideBar.setPreferredSize(new java.awt.Dimension(540, 1040));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome.setBackground(new java.awt.Color(0, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelHomeMouseExited(evt);
            }
        });
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Mongolian Baiti", 0, 28)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnHome.setText("  Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        panelHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 30));

        panelsideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 330, 50));

        panelLogout.setBackground(new java.awt.Color(0, 102, 102));
        panelLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLogoutMouseExited(evt);
            }
        });
        panelLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome1.setFont(new java.awt.Font("Mongolian Baiti", 0, 28)); // NOI18N
        btnHome1.setForeground(new java.awt.Color(255, 255, 255));
        btnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btnHome1.setText("  Logout");
        btnHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHome1MouseClicked(evt);
            }
        });
        panelLogout.add(btnHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 30));

        panelsideBar.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 330, 50));

        panelSearchrecord.setBackground(new java.awt.Color(0, 102, 102));
        panelSearchrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelSearchrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSearchrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSearchrecordMouseExited(evt);
            }
        });
        panelSearchrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome14.setFont(new java.awt.Font("Mongolian Baiti", 0, 28)); // NOI18N
        btnHome14.setForeground(new java.awt.Color(255, 255, 255));
        btnHome14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search2.png"))); // NOI18N
        btnHome14.setText("  Search Record");
        btnHome14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHome14MouseClicked(evt);
            }
        });
        panelSearchrecord.add(btnHome14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 30));

        panelsideBar.add(panelSearchrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 330, 50));

        panelEditcourse.setBackground(new java.awt.Color(0, 102, 102));
        panelEditcourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelEditcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEditcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEditcourseMouseExited(evt);
            }
        });
        panelEditcourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome66.setFont(new java.awt.Font("Mongolian Baiti", 0, 28)); // NOI18N
        btnHome66.setForeground(new java.awt.Color(255, 255, 255));
        btnHome66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btnHome66.setText("  Edit Courses");
        btnHome66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHome66MouseClicked(evt);
            }
        });
        panelEditcourse.add(btnHome66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 30));

        panelsideBar.add(panelEditcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 330, 50));

        panelViewallRec.setBackground(new java.awt.Color(0, 102, 102));
        panelViewallRec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelViewallRec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelViewallRecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelViewallRecMouseExited(evt);
            }
        });
        panelViewallRec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome170.setFont(new java.awt.Font("Mongolian Baiti", 0, 28)); // NOI18N
        btnHome170.setForeground(new java.awt.Color(255, 255, 255));
        btnHome170.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        btnHome170.setText(" View All Records");
        btnHome170.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHome170MouseClicked(evt);
            }
        });
        panelViewallRec.add(btnHome170, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 40));

        panelsideBar.add(panelViewallRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 330, 50));

        panelBack.setBackground(new java.awt.Color(0, 102, 102));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBackMouseExited(evt);
            }
        });
        panelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome222.setFont(new java.awt.Font("Mongolian Baiti", 0, 28)); // NOI18N
        btnHome222.setForeground(new java.awt.Color(255, 255, 255));
        btnHome222.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/back1.png"))); // NOI18N
        btnHome222.setText("  Back");
        btnHome222.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHome222MouseClicked(evt);
            }
        });
        panelBack.add(btnHome222, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 30));

        panelsideBar.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 330, 50));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 810));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_records.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tbl_records.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receipt no", "Roll no", "Student name", "Course name", "Total amount", "Payment mode", "Date", "Remark"
            }
        ));
        tbl_records.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tbl_recordsComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_records);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1030, 650));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("All Record Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 310, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 360, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 1070, 810));

        setSize(new java.awt.Dimension(1534, 817));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void panelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseClicked

    }//GEN-LAST:event_panelHomeMouseClicked

    private void panelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseEntered
        Color clr = new Color(0, 153, 153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_panelHomeMouseEntered

    private void panelHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseExited
        Color clr = new Color(0, 102, 102);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_panelHomeMouseExited

    private void panelLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseEntered
        Color clr = new Color(0, 153, 153);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_panelLogoutMouseEntered

    private void panelLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseExited
        Color clr = new Color(0, 102, 102);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_panelLogoutMouseExited

    private void panelSearchrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchrecordMouseEntered
        Color clr = new Color(0, 153, 153);
        panelSearchrecord.setBackground(clr);
    }//GEN-LAST:event_panelSearchrecordMouseEntered

    private void panelSearchrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchrecordMouseExited
        Color clr = new Color(0, 102, 102);
        panelSearchrecord.setBackground(clr);
    }//GEN-LAST:event_panelSearchrecordMouseExited

    private void panelEditcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditcourseMouseEntered
        Color clr = new Color(0, 153, 153);
        panelEditcourse.setBackground(clr);
    }//GEN-LAST:event_panelEditcourseMouseEntered

    private void panelEditcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditcourseMouseExited
        Color clr = new Color(0, 102, 102);
        panelEditcourse.setBackground(clr);
    }//GEN-LAST:event_panelEditcourseMouseExited

    private void panelViewallRecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewallRecMouseEntered
        Color clr = new Color(0, 153, 153);
        panelViewallRec.setBackground(clr);
    }//GEN-LAST:event_panelViewallRecMouseEntered

    private void panelViewallRecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewallRecMouseExited
        Color clr = new Color(0, 102, 102);
        panelViewallRec.setBackground(clr);
    }//GEN-LAST:event_panelViewallRecMouseExited

    private void panelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBackMouseEntered
        Color clr = new Color(0, 153, 153);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_panelBackMouseEntered

    private void panelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBackMouseExited
        Color clr = new Color(0, 102, 102);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_panelBackMouseExited

    private void tbl_recordsComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tbl_recordsComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_recordsComponentAdded

    private void btnHome14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome14MouseClicked
        SearchRecord sr = new SearchRecord();
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHome14MouseClicked

    private void btnHome66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome66MouseClicked
        EditCourse editCourse = new EditCourse();
        editCourse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHome66MouseClicked

    private void btnHome170MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome170MouseClicked
        viewAllRecords vAllRecords = new viewAllRecords();
        vAllRecords.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHome170MouseClicked

    private void btnHome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome1MouseClicked
        // TODO add your handling code here:
        Login_page login = new Login_page();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHome1MouseClicked

    private void btnHome222MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome222MouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHome222MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewAllRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnHome1;
    private javax.swing.JLabel btnHome14;
    private javax.swing.JLabel btnHome170;
    private javax.swing.JLabel btnHome222;
    private javax.swing.JLabel btnHome66;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelEditcourse;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelSearchrecord;
    private javax.swing.JPanel panelViewallRec;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JTable tbl_records;
    // End of variables declaration//GEN-END:variables
}
